version: "3.9"

services:
  delivery:
    container_name: delivery
    build:
      context: .
      dockerfile: src/Delivery.Service/Dockerfile
    ports:
      - "5003:8080"
      - "5004:8081"
    environment:
      - ConnectionStrings__Npgsql=host=delivery-db;database=delivery_center;username=postgres;password=postgres
    depends_on:
      delivery-db:
        condition: service_healthy
    restart: on-failure

  delivery-db:
    image: postgres:15-alpine
    container_name: delivery-db
    volumes:
      - delivery-db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery_center
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d delivery_center -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  delivery-db:
    driver: local